#!/bin/bash
WATER_DEC=$(( $(echo $WATER | tr 'water' '0-4' | tr -d '.' | fold -w1 | tac | awk '{s+=$1*5^NR} END{print s-=$1}') + $(echo $STIR | tr 'stir' '0-3' | tr -d '.' | fold -w1 | tac | awk '{s+=$1*4^NR} END{print s-=$1}') ))
[ $WATER_DEC -eq 0 ] && echo b || echo $WATER_DEC | awk '{while($1>0){r=$1%8;$1=int($1/8);d=r d}print d}' | tr '0-7' 'bestchol'
