#!/bin/env bash
#Installs and cinfigs ngix to listen on port 80

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir -p /var/www/html/

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i 's/^\(listen\s\+\)80/\1listen 80/' /etc/nginx/sites-available/default

sudo /etc/init.d/nginx restart

sudo ufw allow 'Nginx HTTP'
sudo ufw --force enable
