#!/usr/bin/env bash
#Installs and cinfigs ngix to listen on port 80
#with default, 404,  and redirection page

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir -p /var/www/html/
sudo mkdir -p /usr/share/nginx/html
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/page_error_404.html

sudo sed -i "/listen 80 default_server;a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGU1wu4 permanent;" /etc/nginx/sites-enabled/default

#sudo sed -i 's/^\(listen\s\+\)80/\1listen 80/' /etc/nginx/sites-available/default

sudo sed -i '37i error_page 404 /page_error_404.html;\nlocation = /page_error_404.html {\nroot /usr/share/nginx/html; \ninternal;\n}\n' /etc/nginx/sites-enabled/default

sudo nginx -t
sudo /etc/init.d/nginx restart
