#!/usr/bin/env bash
#Installs and cinfigs ngix to listen on port 80
#with default, 404,  and redirection page

sudo apt-get update
sudo apt-get install -y nginx

REDIRECT_301="\\
    location /redirect_me {\\
        return 301 https://www.youtube.com/watch?v=QH2-TGU1wu4;\\
    }\\
"
NOTFOUND_404="\
     error_page 404 /custom_404.html;\
     location = /custom_404.html {\
         root /usr/share/nginx/html;\
        internal;\
     }\
"
#PATTERN="#error_page 404 /404.html;"

#sudo mkdir -p /var/www/html/

echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

sudo sed -i '/location \/redirect_me {/,/}/d' /etc/nginx/sites-available/default
sudo sed -i "30i $REDIRECT_301" /etc/nginx/sites-available/default

#sudo sed -i 's/^\(listen\s\+\)80/\1listen 80/' /etc/nginx/sites-available/default

sudo sed -i "s@\#error_page 404 /404.html;@$NOTFOUND_404@" /etc/nginx/sites-available/default
sudo nginx -t
sudo /etc/init.d/nginx restart
