#!/usr/bin/env bash
#creates infinite loop
#creates a file /var/run/myscript.pid containing its PID,
#displays To infinity and beyonf dindefinitely, I hate 
#the kill command, Y U no Love me when receiving
#SIGINT signal, deletes created file and terminates when receive
#whenSIGQUIt(ctrl-| or SIGTERM(kill)


del_quit()
{
	rm -f /var/run/myscript.pid;
	exit
}
trap "echo 'I hate the kill command'; del_quit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command'; del_quit" SIGQUIT

echo $$ >> /var/run/myscript.pid
while (true)
do
	echo 'To infinity and beyond'
	sleep 2
done
