#!/usr/bin/env bash
#This script is displaying "Best School" 10 time
#s and strings at 8

my_string="Best School"

count=0

while [ $count -lt 10 ]
do
    if [[ $count == 8 ]]; then
        echo "$my_string"
        echo "Hi"
    else
        echo "$my_string"
    fi
    ((count++))
done
