#!/usr/bin/env bash
#install ufw firewall, block incoming except 22,443,80

sudo apt-get update
sudo apt-get install -y ufw
sudo ufw --force reset
sudo sed -i "s/IPV6=no/IPV6=yes/" /etc/default/ufw

sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

sudo ufw --force enable
sudo ufw status verbose
