#!/usr/bin/env bash
# runs nginx as nginx
sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-available/default
sudo pkill apache2
sudo -u nginx service nginx restart
