#!/usr/bin/env bash
#runs nginx as nginx
sudo chown -R nginx:nginx /var/log/nginx
sudo chown -R nginx:nginx /var/lib/nginx
sudo sed -i 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-available/default
sudo service nginx restart
