#!/usr/bin/env bash
# connect to server with private rsa ssh key

# private_key="~/.ssh/school"
# user="ubuntu"
# server="100.25.145.4"

#ssh -i "$private_key" "$user"@"$server" >/dev/null 2>&1
ssh -i ~/.ssh/school ubuntu@100.25.145.4
